services:

  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      MONGO_HOST: mongodb
      MONGO_USERNAME: root
      MONGO_PASSWORD: secret
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: myuser
      RABBITMQ_PASSWORD: secret

  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=ww-base'
      - 'MONGO_INITDB_ROOT_PASSWORD=secret'
      - 'MONGO_INITDB_ROOT_USERNAME=root'
    ports:
      - '27017:27017'

  rabbitmq:
    image: pcloud/rabbitmq-stomp
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"
    volumes:
      - '~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/'

volumes:
  rabbitmq: