version: '3.8'

services:
  server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - rabbitmq
    environment:
      MONGO_HOST: 192.168.0.5
      MONGO_USERNAME: gen_user
      MONGO_PASSWORD: o7;zGs516}u(jl
      RABBITMQ_HOST: rabbitmq
      RABBITMQ_USERNAME: myuser
      RABBITMQ_PASSWORD: secret
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE}


  rabbitmq:
    image: pcloud/rabbitmq-stomp
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: myuser
      RABBITMQ_DEFAULT_PASS: secret
    ports:
      - "5672:5672"
      - "15672:15672"
      - "61613:61613"


