spring:


  application:
    name: antiyoyo

  rabbitmq:
    host: localhost
    username: myuser
    password: secret

  data:
    mongodb:
      host: localhost
      database: mydatabase
      username: root
      password: secret

