spring:

  application:
    name: antiyoyo

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    username: ${RABBITMQ_USERNAME:myuser}
    password: ${RABBITMQ_PASSWORD:secret}

  data:
    mongodb:
      uuid-representation: standard
      host: ${MONGO_HOST:192.168.0.5}
      authentication-database: admin
      database: ww-game
      username: ${MONGO_USERNAME:gen_user}
      password: ${MONGO_PASSWORD:qwertyZ1%}

management:
  endpoint:
#    configprops:
#      show-values: ALWAYS
#    env:
#      show-values: ALWAYS
    health:
      show-details: always  # Подробный вывод здоровья
    shutdown:
      enabled: true         # Разрешить graceful shutdown (POST /actuator/shutdown)
  endpoints:
    web:
      exposure:
        include: "*"        # Открыть все эндпоинты
      base-path: /actuator  # Базовый путь (по умолчанию /actuator)

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG
